"""empty message

Revision ID: 1664ce689f3e
Revises: 0fcf95a287cc
Create Date: 2024-03-14 11:18:19.763886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1664ce689f3e'
down_revision = '0fcf95a287cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('date_set', sa.DateTime(), nullable=False))
    op.alter_column('city', 'state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('city', 'data_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('data_set', sa.DATETIME(), nullable=False))
    op.alter_column('city', 'state',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('city', 'date_set')
    # ### end Alembic commands ###
